var x = window.matchMedia("(max-width: 1150px)");
icons(x); // Call listener function at run time
x.addListener(icons); // Attach listener function on state changes


function icons(x) {
  if (x.matches) { // If media query matches
    document.getElementById("skills-bar").innerHTML ="";
  } else {
    document.getElementById("skills-bar").innerHTML ="<div class='container skills-bar'><div class='row'><div class='icons col-lg-12'><img src='/Images/java-script.png' class='js icon-size' alt=''...''><img src='/Images/VBA Icon.png' class='vba icon-size' alt=''...''><img src='/Images/VB Icon.png' class='vb icon-size' alt='...'>                <img src='/Images/html-5 (1).png' class='htmlIcon icon-size' alt='...'>                <img src='/Images/Visual Basic Icon.png' class='vbsIcon icon-size' alt='...'>                <img src='/Images/sql.png' class='sql icon-size' alt='...'>                <img src='/Images/react.png' class='react icon-size' alt='...'>                <img src='/Images/nodejs.png' class='nodeJS icon-size' alt='...'>                <img src='/Images/figma.png' class='figma icon-size' alt='...'>                <img src='/Images/css-3.png' class='cssIcon icon-size' alt='...'>                <img src='/Images/adroid studio.png' class='android icon-size' alt='...'>                <img src='/Images/java.png' class='java icon-size' alt='...'>              </div>            </div>          </div>            <div class='container skills-bar'>            <div class='row'>              <div class='icons2 col-lg-12'>                <img src='/Images/java-script.png' class='js icon-size' alt='...'>                <img src='/Images/VBA Icon.png' class='vba icon-size' alt='...'>                <img src='/Images/VB Icon.png' class='vb icon-size' alt='...'>                <img src='/Images/html-5 (1).png' class='htmlIcon icon-size' alt='...'>                <img src='/Images/Visual Basic Icon.png' class='vbsIcon icon-size' alt='...'>                <img src='/Images/sql.png' class='sql icon-size' alt='...'>                <img src='/Images/react.png' class='react icon-size' alt='...'>                <img src='/Images/nodejs.png' class='nodeJS icon-size' alt='...'>                <img src='/Images/figma.png' class='figma icon-size' alt='...'>                <img src='/Images/css-3.png' class='cssIcon icon-size' alt='...'>                <img src='/Images/adroid studio.png' class='android icon-size' alt='...'>                <img src='/Images/java.png' class='java icon-size' alt='...'>              </div>            </div>          </div>";
  }
}